# host_vars/lampstack.yml
---

el7_repositories:
  - epel-release

el7_install_packages:
  - policycoreutils
  - setroubleshoot-server

el7_firewall_allow_services:
  - http
  - https
  - dns

httpd_scripting: 'php'

mariadb_databases:
  - wordpress

mariadb_users:
  - name: admin
    password: admin
    priv: 'wordpress.*:ALL'

mariadb_root_password: admin

wordpress_database: wordpress
wordpress_user: admin
wordpress_password: admin
